<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Ambil ID kategori
        $lantai    = Category::where('slug', 'lantai')->first()->id;
        $dinding   = Category::where('slug', 'dinding')->first()->id;
        $kamarMandi = Category::where('slug', 'kamar-mandi')->first()->id;
        $dapur     = Category::where('slug', 'dapur')->first()->id;
        $teras     = Category::where('slug', 'teras')->first()->id;

        $products = [
            // ===== LANTAI =====
            [
                'sku'         => 'LNT-001',
                'name'        => 'Granit Putih Polos 60x60',
                'category_id' => $lantai,
                'price'       => 85000,
                'stock'       => 500,
                'description' => 'Granit putih polos cocok untuk ruang tamu dan ruang keluarga. Permukaan glossy memantulkan cahaya dengan indah.',
                'size'        => '60x60',
                'motif'       => 'Polos',
                'brand'       => 'Ferdi',
                'color'       => 'Putih',
                'finish'      => 'Glossy',
                'is_available' => true,
            ],
            [
                'sku'         => 'LNT-002',
                'name'        => 'Granit Marbel Abu 60x60',
                'category_id' => $lantai,
                'price'       => 95000,
                'stock'       => 350,
                'description' => 'Motif marmer abu-abu elegan untuk ruang tamu modern. Anti selip dan tahan lama.',
                'size'        => '60x60',
                'motif'       => 'Marmer',
                'brand'       => 'Ferdi',
                'color'       => 'Abu-abu',
                'finish'      => 'Glossy',
                'is_available' => true,
            ],
            [
                'sku'         => 'LNT-003',
                'name'        => 'Keramik Kayu Natural 30x60',
                'category_id' => $lantai,
                'price'       => 75000,
                'stock'       => 420,
                'description' => 'Motif kayu natural memberikan kesan hangat dan alami pada ruangan.',
                'size'        => '30x60',
                'motif'       => 'Kayu',
                'brand'       => 'Ferdi',
                'color'       => 'Coklat',
                'finish'      => 'Matte',
                'is_available' => true,
            ],
            [
                'sku'         => 'LNT-004',
                'name'        => 'Granit Hitam Polos 80x80',
                'category_id' => $lantai,
                'price'       => 150000,
                'stock'       => 200,
                'description' => 'Granit hitam mewah ukuran besar untuk kesan modern dan elegan.',
                'size'        => '80x80',
                'motif'       => 'Polos',
                'brand'       => 'Ferdi',
                'color'       => 'Hitam',
                'finish'      => 'Glossy',
                'is_available' => true,
            ],
            [
                'sku'         => 'LNT-005',
                'name'        => 'Keramik Motif Batu 40x40',
                'category_id' => $lantai,
                'price'       => 55000,
                'stock'       => 600,
                'description' => 'Keramik dengan motif batu alam, cocok untuk area semi outdoor.',
                'size'        => '40x40',
                'motif'       => 'Batu',
                'brand'       => 'Ferdi',
                'color'       => 'Krem',
                'finish'      => 'Matte',
                'is_available' => true,
            ],

            // ===== DINDING =====
            [
                'sku'         => 'DND-001',
                'name'        => 'Keramik Dinding Putih 25x40',
                'category_id' => $dinding,
                'price'       => 45000,
                'stock'       => 800,
                'description' => 'Keramik dinding putih bersih, cocok untuk semua jenis ruangan.',
                'size'        => '25x40',
                'motif'       => 'Polos',
                'brand'       => 'Ferdi',
                'color'       => 'Putih',
                'finish'      => 'Glossy',
                'is_available' => true,
            ],
            [
                'sku'         => 'DND-002',
                'name'        => 'Keramik Dinding Motif Batik 25x40',
                'category_id' => $dinding,
                'price'       => 65000,
                'stock'       => 300,
                'description' => 'Keramik dinding motif batik khas Indonesia, memberikan sentuhan budaya lokal.',
                'size'        => '25x40',
                'motif'       => 'Batik',
                'brand'       => 'Ferdi',
                'color'       => 'Biru',
                'finish'      => 'Glossy',
                'is_available' => true,
            ],
            [
                'sku'         => 'DND-003',
                'name'        => 'Keramik Dinding 3D Batu Bata 30x60',
                'category_id' => $dinding,
                'price'       => 85000,
                'stock'       => 250,
                'description' => 'Keramik dinding tekstur 3D motif batu bata untuk aksen dinding yang unik.',
                'size'        => '30x60',
                'motif'       => 'Batu Bata',
                'brand'       => 'Ferdi',
                'color'       => 'Merah Bata',
                'finish'      => 'Matte',
                'is_available' => true,
            ],

            // ===== KAMAR MANDI =====
            [
                'sku'         => 'KMD-001',
                'name'        => 'Keramik Kamar Mandi Anti Slip 20x20',
                'category_id' => $kamarMandi,
                'price'       => 35000,
                'stock'       => 700,
                'description' => 'Keramik anti selip khusus lantai kamar mandi, aman untuk anak-anak.',
                'size'        => '20x20',
                'motif'       => 'Polos',
                'brand'       => 'Ferdi',
                'color'       => 'Putih',
                'finish'      => 'Anti Slip',
                'is_available' => true,
            ],
            [
                'sku'         => 'KMD-002',
                'name'        => 'Keramik Kamar Mandi Motif Laut 25x40',
                'category_id' => $kamarMandi,
                'price'       => 55000,
                'stock'       => 400,
                'description' => 'Keramik dinding kamar mandi motif laut biru, menciptakan suasana segar.',
                'size'        => '25x40',
                'motif'       => 'Laut',
                'brand'       => 'Ferdi',
                'color'       => 'Biru',
                'finish'      => 'Glossy',
                'is_available' => true,
            ],
            [
                'sku'         => 'KMD-003',
                'name'        => 'Granit Kamar Mandi Abu Matte 30x30',
                'category_id' => $kamarMandi,
                'price'       => 65000,
                'stock'       => 320,
                'description' => 'Granit matte abu-abu modern untuk kamar mandi minimalis.',
                'size'        => '30x30',
                'motif'       => 'Polos',
                'brand'       => 'Ferdi',
                'color'       => 'Abu-abu',
                'finish'      => 'Matte',
                'is_available' => true,
            ],

            // ===== DAPUR =====
            [
                'sku'         => 'DPR-001',
                'name'        => 'Keramik Dapur Putih Glossy 20x40',
                'category_id' => $dapur,
                'price'       => 42000,
                'stock'       => 550,
                'description' => 'Keramik dapur putih glossy mudah dibersihkan, cocok untuk backsplash.',
                'size'        => '20x40',
                'motif'       => 'Polos',
                'brand'       => 'Ferdi',
                'color'       => 'Putih',
                'finish'      => 'Glossy',
                'is_available' => true,
            ],
            [
                'sku'         => 'DPR-002',
                'name'        => 'Keramik Dapur Motif Subway 10x30',
                'category_id' => $dapur,
                'price'       => 38000,
                'stock'       => 480,
                'description' => 'Keramik subway tile klasik untuk dapur bergaya retro modern.',
                'size'        => '10x30',
                'motif'       => 'Subway',
                'brand'       => 'Ferdi',
                'color'       => 'Putih',
                'finish'      => 'Glossy',
                'is_available' => true,
            ],
            [
                'sku'         => 'DPR-003',
                'name'        => 'Keramik Dapur Hexagon 20x20',
                'category_id' => $dapur,
                'price'       => 58000,
                'stock'       => 300,
                'description' => 'Keramik hexagon unik untuk lantai dapur bergaya modern.',
                'size'        => '20x20',
                'motif'       => 'Hexagon',
                'brand'       => 'Ferdi',
                'color'       => 'Hitam Putih',
                'finish'      => 'Matte',
                'is_available' => true,
            ],

            // ===== TERAS =====
            [
                'sku'         => 'TRS-001',
                'name'        => 'Keramik Teras Anti Slip 40x40',
                'category_id' => $teras,
                'price'       => 48000,
                'stock'       => 650,
                'description' => 'Keramik teras anti selip tahan cuaca, cocok untuk area outdoor.',
                'size'        => '40x40',
                'motif'       => 'Polos',
                'brand'       => 'Ferdi',
                'color'       => 'Abu-abu',
                'finish'      => 'Anti Slip',
                'is_available' => true,
            ],
            [
                'sku'         => 'TRS-002',
                'name'        => 'Keramik Carport Batu Alam 40x40',
                'category_id' => $teras,
                'price'       => 62000,
                'stock'       => 400,
                'description' => 'Keramik motif batu alam kuat dan tahan beban untuk carport.',
                'size'        => '40x40',
                'motif'       => 'Batu Alam',
                'brand'       => 'Ferdi',
                'color'       => 'Coklat',
                'finish'      => 'Anti Slip',
                'is_available' => true,
            ],
            [
                'sku'         => 'TRS-003',
                'name'        => 'Keramik Teras Motif Kayu 20x80',
                'category_id' => $teras,
                'price'       => 78000,
                'stock'       => 280,
                'description' => 'Keramik teras motif kayu panjang untuk teras yang terlihat natural.',
                'size'        => '20x80',
                'motif'       => 'Kayu',
                'brand'       => 'Ferdi',
                'color'       => 'Coklat Muda',
                'finish'      => 'Matte',
                'is_available' => true,
            ],
            [
                'sku'         => 'LNT-006',
                'name'        => 'Granit Krem Marmer 60x60',
                'category_id' => $lantai,
                'price'       => 110000,
                'stock'       => 0,
                'description' => 'Granit krem motif marmer mewah. Saat ini sedang habis stok.',
                'size'        => '60x60',
                'motif'       => 'Marmer',
                'brand'       => 'Ferdi',
                'color'       => 'Krem',
                'finish'      => 'Glossy',
                'is_available' => false,
            ],
            [
                'sku'         => 'DND-004',
                'name'        => 'Keramik Dinding Hijau Sage 25x40',
                'category_id' => $dinding,
                'price'       => 52000,
                'stock'       => 180,
                'description' => 'Keramik dinding warna hijau sage elegan untuk ruang tamu modern.',
                'size'        => '25x40',
                'motif'       => 'Polos',
                'brand'       => 'Ferdi',
                'color'       => 'Hijau',
                'finish'      => 'Matte',
                'is_available' => true,
            ],
            [
                'sku'         => 'KMD-004',
                'name'        => 'Mosaik Kamar Mandi 30x30',
                'category_id' => $kamarMandi,
                'price'       => 95000,
                'stock'       => 150,
                'description' => 'Keramik mosaik premium untuk kamar mandi mewah.',
                'size'        => '30x30',
                'motif'       => 'Mosaik',
                'brand'       => 'Ferdi',
                'color'       => 'Multi',
                'finish'      => 'Glossy',
                'is_available' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}