[phases.setup]
nixPkgs = ["php81", "php81Extensions.pdo_mysql", "php81Extensions.mbstring", "php81Extensions.xml", "php81Extensions.zip", "php81Extensions.gd", "composer"]

[phases.build]
cmds = ["composer install --no-dev --ignore-platform-reqs", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"